format = """
$directory\
$git_branch\
$git_status\
$cmd_duration\
$line_break\
$character"""

[directory]
style = "bold white"
truncation_length = 3
truncate_to_repo = true

[character]
success_symbol = "[\\$](bold white)"
error_symbol = "[\\$](bright-black)"

[git_branch]
symbol = ""
style = "bright-black"
format = " [$branch]($style)"

[git_status]
style = "bright-black"
format = " ([$all_status$ahead_behind]($style))"

[cmd_duration]
min_time = 500
style = "bright-black"
format = " [$duration]($style)"

[golang]
disabled = true

[python]
disabled = true
