# Main format
format = """
$directory\
$git_branch\
$git_status\
$line_break\
$character"""

# Space between command outputs
add_newline = true

[line_break]
disabled = false

[character]
success_symbol = "[❯](bold #a3be8c)" # Nord green
error_symbol = "[❯](bold #bf616a)"   # Nord red

[directory]
style = "bold #81a1c1" # Nord frost blue
truncation_length = 3
truncate_to_repo = true

[git_branch]
symbol = " "
style = "bold #b48ead" # Nord purple
format = "[$symbol$branch]($style) "

[git_status]
style = "bold #bf616a" # Nord red
format = '([$all_status$ahead_behind]($style) )'
