set -g prefix c-space
set -g mouse on

# Sensible
set -g history-limit 50000
set -s escape-time 0
set -g display-time 4000
set -g status-interval 5
set -g focus-events on
setw -g aggressive-resize on
set -g allow-passthrough on

# Colorscheme
set -g status-style bg=default,fg=white
set -g status-justify centre
set -g status-left ' #[fg=white,bold]#S #[fg=colour240] '
set -g status-right ' #[fg=white]%b %d #[fg=colour240]│ #[fg=white]%H:%M '
set -g status-left-length 50
set -g window-status-format ' #[fg=colour240]#I:#W '
set -g window-status-current-format ' #[fg=white,bold]#I:#W '
set -g pane-border-style fg=colour239
set -g pane-active-border-style fg=white
set -g message-style bg=default,fg=white
set -g mode-style bg=colour240,fg=black
set -g menu-selected-style bg=colour240,fg=black

# Remaps
bind - split-window -v -c "#{pane_current_path}"
bind | split-window -h -c "#{pane_current_path}"
bind -r j resize-pane -D 10
bind -r k resize-pane -U 10
bind -r l resize-pane -R 10
bind -r h resize-pane -L 10

# Vim tmux
is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|l?n?vim?x?|fzf)(diff)?$'"
bind-key -n 'C-h' if-shell "$is_vim" 'send-keys C-h'  'select-pane -L'
bind-key -n 'C-j' if-shell "$is_vim" 'send-keys C-j'  'select-pane -D'
bind-key -n 'C-k' if-shell "$is_vim" 'send-keys C-k'  'select-pane -U'
bind-key -n 'C-l' if-shell "$is_vim" 'send-keys C-l'  'select-pane -R'

# Vi-mode
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi i send-keys -X cancel
bind-key -T copy-mode-vi a send-keys -X cancel
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection
unbind -T copy-mode-vi mousedragend1pane

# Plugins
set -g @plugin 'tmux-plugins/tpm'

# Initialize tpm
run '~/.config/tmux/plugins/tpm/tpm'
