set -g prefix C-Space
set -g mouse on

set-environment -g TMUX_PLUGIN_MANAGER_PATH '~/.config/tmux/plugins/'

# Tmux plugin manager
set -g @plugin 'tmux-plugins/tpm'

# Common-sense default
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'

# Colorscheme
set -g @plugin "arcticicestudio/nord-tmux"

# --- SESSION SAVING PLUGINS ---
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

set -g @resurrect-capture-pane-contents 'on'
set -g @resurrect-save 'S'
set -g @resurrect-restore 'R'
set -g @continuum-save-interval '9'
# set -g @continuum-restore 'on'

set -g allow-passthrough on

bind - split-window -v -c "#{pane_current_path}"
bind | split-window -h -c "#{pane_current_path}"

# Remap for resize pane
bind -r j resize-pane -D 10
bind -r k resize-pane -U 10
bind -r l resize-pane -R 10
bind -r h resize-pane -L 10

# Smart pane switching with awareness of Vim splits
is_vim="ps -o state= -o comm= -t '#{pane_tty}' | grep -iqE 'vim|nvim'"
bind -n C-h if-shell "$is_vim" "send-keys C-h" "select-pane -L"
bind -n C-j if-shell "$is_vim" "send-keys C-j" "select-pane -D"
bind -n C-k if-shell "$is_vim" "send-keys C-k" "select-pane -U"
bind -n C-l if-shell "$is_vim" "send-keys C-l" "select-pane -R"

# Set vi-mode
set-window-option -g mode-keys vi

# Vim like copy
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection
unbind -T copy-mode-vi MouseDragEnd1Pane

# Initialize tmux plugin manager (MUST BE THE LAST LINE)
run '~/.config/tmux/plugins/tpm/tpm'

